### ISSUE TITLE
Old dependency of @primer/primitives require node v18

### ISSUE THREAD

**Issue by jophy-ye** [datalayer/primer-addons#36]
## Description
Can we please move on from `"@primer/primitives": "^8.2.3"` to [v9 or v10](https://github.com/primer/primitives/releases)? I know they haven't been released for a long time, but v8.2.4 requires `"node": ">=18.18.0 <18.19.0"`, which is only supported until 2025. (Another reason is that my environment uses node v22, though strictly speaking I can `--ignore-engines` but it's not the best idea.) Later versions of the package do not require node v18. Is there a specific reason we cannot bump its version?

https://github.com/datalayer/primer-addons/blob/9ac72605eae0a81a19779481d247f3f3e4d4ddf7/package.json#L28

**Comment by echarles** [comment]
Thank you @jophy-ye We have merged https://github.com/datalayer/primer-addons/pull/37 (which removes that dependency, at some point some time ago, that has been needed to ensure compilation, but we don't use it directly, so good to simply remove it).

`0.3.2` is released with that change https://www.npmjs.com/package/@datalayer/primer-addons/v/0.3.2

**Comment by jophy-ye** [comment]
@echarles @fcollonval Thanks! Pre-happy holiday!
