### ISSUE TITLE
Create a Card component

### ISSUE THREAD

**Issue by echarles** [datalayer/primer-addons#6]
A bit like https://mui.com/material-ui/react-card with 

- Title
- Description
- Icon
- Link

```ts
<Card>
  <Card.Header 
    title="The title" 
    description="The description" 
    leadingIcon={TheLeadingIcon}
    trailingIcon={TheTrailingIcon}
  >
     The header content
  </Card.Header>
  <Card.Body
     backgroundImage={...}
  >
    The card body
  </Card.Body>
  <Card.Footer>
    The card footer
  </Card.Fotter>
</Card>
```

**Comment by im-adithya** [comment]
Found this package: https://primer.style/brand/components/Card
Ig this issue can be closed now.

**Comment by echarles** [comment]
This would demand to add the @primer/brand package as additional dependency
@primer/react and @primer/brand are complementary, and not directly aimed to be used on the same page.

We can use it for now in the jupyter-manager and leave this issue open for later discussion.
